import React, { useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head'
import Image from 'next/image'

import Wallet from '../components/dashboard/wallet/Wallet';
import Transfers from '../components/dashboard/transfers/Transfers';

import logo from '../assets/logo-ngcash.svg'
import styles from '../../styles/Dashboard.module.css'
import Cookies from 'js-cookie';

export default function Dashboard() {
  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
  }
  const router = useRouter()

  useEffect(() => {
    const cookie: any = Cookies.get("logado");
    if (cookie) {
      router.push("dashboard/")
    } else {
      router.push("/")
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image className={styles.logo} src={logo} alt="Logo NG Cash" />

      <main className={styles.main}>

        <div className='container'>
          <div className={styles.container_grid__2}>

            <Wallet />

            <Transfers />
          </div>
        </div>
      </main>
    </div>
  )
}
